In [25]:
import numpy as np


x=np.arange(100,dtype=np.uint16)
x[25],x[50],x[75]=3,3,3
zero=np.array([0],dtype=np.uint8)
last=120


eot_indicies=np.where(x[:-1]==3)[0]

cuseq=np.zeros(eot_indicies.shape[0]+2)
cuseq[-1]=x.shape[0]
idx=np.arange(eot_indicies.shape[0])

cuseq[idx+1]=eot_indicies[idx]
print(cuseq)

cumsum_rope=np.concatenate([np.arange(cuseq[i+1]-cuseq[i]) for i in range(len(cuseq)-1)])

eot_indicies,cumsum_rope,cuseq,len(cumsum_rope)



[  0.   3.  25.  50.  75. 100.]


(array([ 3, 25, 50, 75]),
 array([ 0.,  1.,  2.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.,
        10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.,  0.,
         1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,  0.,  1.,
         2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,  0.,  1.,  2.,
         3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
        16., 17., 18., 19., 20., 21., 22., 23., 24.]),
 array([  0.,   3.,  25.,  50.,  75., 100.]),
 100)